/**
 * SP-F-15 Control de oficios (2026) — catálogo oficial
 * Rev. seed: 2026-06-23-133
 */
const OFICIOS_SEED_REV = '2026-06-23-133';

const OFICIOS_SEED = [
  { numero_oficio: 1, empresa: 'TIZAQUIM CANDELARIA', motivo: 'INGRESO PC ESTADO' },
  { numero_oficio: 2, empresa: 'TIZAQUIM CANDELARIA', motivo: 'Cart correspomsablidad estado' },
  { numero_oficio: 3, empresa: 'TIZAQUIM CANDELARIA', motivo: 'Carta pode Estado' },
  { numero_oficio: 4, empresa: 'ADHESIVOS', motivo: 'Oficio RME SEMARNATH' },
  { numero_oficio: 5, empresa: 'CREST', motivo: 'Oficio RME SEMARNATH' },
  { numero_oficio: 6, empresa: 'BOMBAS GOULDS', motivo: 'Oficio RME SEMARNATH' },
  { numero_oficio: 7, empresa: 'Estacionamiento, lavado y pensión', motivo: 'Oficio presentación PC' },
  { numero_oficio: 8, empresa: 'Estacionamiento, lavado y pensión', motivo: 'Oficio Carta  Corresponsabilidad' },
  { numero_oficio: 9, empresa: 'Estacionamiento, lavado y pensión', motivo: 'Constancias medidas de seguridad' },
  { numero_oficio: 10, empresa: 'Estacionamiento, lavado y pensión', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 11, empresa: 'Candelaria', motivo: 'Oficio de modelaciones PIPC' },
  { numero_oficio: 12, empresa: 'El Marques', motivo: 'Oficio Licencia uso suelo' },
  { numero_oficio: 13, empresa: 'Cargill', motivo: 'Oficio OTMS Cargill' },
  { numero_oficio: 14, empresa: 'Cargill', motivo: 'Carta poder Cargill' },
  { numero_oficio: 15, empresa: '', motivo: '' },
  { numero_oficio: 16, empresa: 'COMEX', motivo: 'Condicionantes DcyE 3921' },
  { numero_oficio: 17, empresa: 'SYCSA', motivo: 'Oficio seguimiento OTMS ' },
  { numero_oficio: 18, empresa: 'BIZNAGA', motivo: 'oficio consultor Tula ' },
  { numero_oficio: 19, empresa: 'Sunshine ', motivo: 'Oficio RME SEMARNATH' },
  { numero_oficio: 20, empresa: 'El Marques', motivo: 'Oficio DGNA 261 Semarnath' },
  { numero_oficio: 21, empresa: 'Trituradora', motivo: 'Oficio CONAGUA ' },
  { numero_oficio: 22, empresa: 'Trituradora', motivo: 'Condicionantes anuales trituracion' },
  { numero_oficio: 23, empresa: 'Trituradora', motivo: 'Condicionanles LAE' },
  { numero_oficio: 24, empresa: 'Trituradora', motivo: 'Condicionantes anuales explotación' },
  { numero_oficio: 25, empresa: 'Trituradora', motivo: 'Solicitud Bitácora' },
  { numero_oficio: 26, empresa: 'MEMOS ', motivo: 'PIPC MUNICIPIO ' },
  { numero_oficio: 27, empresa: 'MEMOS ', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 28, empresa: 'MEMOS ', motivo: 'Constancias medidas de seguridad' },
  { numero_oficio: 29, empresa: 'MEMOS ', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 30, empresa: 'Sunshine ', motivo: 'Carta poder   ' },
  { numero_oficio: 31, empresa: 'SQG', motivo: 'oficio PC ' },
  { numero_oficio: 32, empresa: 'SQG', motivo: 'OTMS municipio' },
  { numero_oficio: 33, empresa: 'SQG', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 34, empresa: "CARL´S TULA ", motivo: 'Oficio presentación PC' },
  { numero_oficio: 35, empresa: "CARL´S TULA ", motivo: 'OTMS municipio' },
  { numero_oficio: 36, empresa: "CARL´S TULA ", motivo: 'CARTA DE CORRESPONSABILIDAD+' },
  { numero_oficio: 37, empresa: 'EL HADA ', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 38, empresa: 'EL HADA ', motivo: 'OFICIO INGRESO PC' },
  { numero_oficio: 39, empresa: 'EL HADA ', motivo: 'OPINION TECNICA ' },
  { numero_oficio: 40, empresa: 'EL HADA ', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 41, empresa: "CARL´S PACHUCA ", motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 42, empresa: "CARL´S PACHUCA ", motivo: 'OFICIO INGRESO PC' },
  { numero_oficio: 43, empresa: "CARL´S PACHUCA ", motivo: 'OPINION TECNICA ' },
  { numero_oficio: 44, empresa: "CARL´S PACHUCA ", motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 45, empresa: 'EL HADA ', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 46, empresa: 'CREST', motivo: 'Oficio botacora control polvo' },
  { numero_oficio: 47, empresa: 'MAESA', motivo: 'condicionantes anuales' },
  { numero_oficio: 48, empresa: 'SANIMEX', motivo: '' },
  { numero_oficio: 49, empresa: 'SANIMEX', motivo: '' },
  { numero_oficio: 50, empresa: 'SANIMEX', motivo: '' },
  { numero_oficio: 51, empresa: 'SYCA', motivo: 'contestación PC SYCSA ' },
  { numero_oficio: 52, empresa: 'MORGAN', motivo: 'PC seguimiento' },
  { numero_oficio: 53, empresa: 'SYCSA', motivo: 'carta poder' },
  { numero_oficio: 54, empresa: 'SUNSHINE', motivo: 'oficio acuerdo RME' },
  { numero_oficio: 55, empresa: 'MORGAN', motivo: 'oficio PC ' },
  { numero_oficio: 56, empresa: 'MORGAN', motivo: 'medidas seguridad' },
  { numero_oficio: 57, empresa: 'MORGAN', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 58, empresa: 'Estacionamiento Español', motivo: 'Oficio PC ' },
  { numero_oficio: 60, empresa: 'Estacionamiento Español', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 61, empresa: 'Estacionamiento Español', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 62, empresa: 'Estacionamiento Español', motivo: 'OTMS municipio Pachuca ' },
  { numero_oficio: 63, empresa: 'Ortiz Fitnes', motivo: 'Ingreso PC Epazoyucam' },
  { numero_oficio: 64, empresa: 'Ortiz Fitnes', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 65, empresa: 'Ortiz Fitnes', motivo: 'Oficio de OTMS' },
  { numero_oficio: 66, empresa: 'Ortiz Fitnes', motivo: 'Carta compromiso licencia funcionamiento' },
  { numero_oficio: 67, empresa: 'Trituradora', motivo: 'Oficio SEMARNATH DGNA/DCyE-164/2026' },
  { numero_oficio: 68, empresa: 'Trituradora', motivo: 'Carta poder ' },
  { numero_oficio: 69, empresa: 'Trituradora', motivo: 'Oficio seguimiento OTMS ' },
  { numero_oficio: 70, empresa: 'PERDURA', motivo: 'Oficio DcyE-5271 PERDURA' },
  { numero_oficio: 71, empresa: 'Trituradora', motivo: 'Oficio SEMARNATH DGNA/DCyE-160/2026' },
  { numero_oficio: 72, empresa: 'Trituradora', motivo: 'Oficio SEMARNATH DGNA/DCyE-612/2026' },
  { numero_oficio: 73, empresa: 'MORGAN', motivo: 'Carta poder' },
  { numero_oficio: 74, empresa: 'MAESA', motivo: 'oficio de PC inspección' },
  { numero_oficio: 75, empresa: 'EAD', motivo: 'Ingreso PC Pachuca ' },
  { numero_oficio: 76, empresa: 'EAD', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 77, empresa: 'EAD', motivo: 'Oficio de OTMS' },
  { numero_oficio: 78, empresa: 'BOMBAS GOULDS', motivo: 'Resello ' },
  { numero_oficio: 79, empresa: 'FLORESTA', motivo: 'condicionantes anuales' },
  { numero_oficio: 80, empresa: 'ARGENTA RESIDENCIAL', motivo: 'Ampliación de vigencia' },
  { numero_oficio: 81, empresa: 'ARGENTA RESIDENCIAL', motivo: 'seguimiento condicionantes ' },
  { numero_oficio: 82, empresa: 'candelaria', motivo: 'CARTA CORRESPONSABILIDAD' },
  { numero_oficio: 83, empresa: 'candelaria', motivo: 'carta poder' },
  { numero_oficio: 84, empresa: 'candelaria', motivo: 'oficio PC municipio ' },
  { numero_oficio: 85, empresa: 'carta compromiso Licencia uso suelo', motivo: 'oficio PC municipio ' },
  { numero_oficio: 86, empresa: 'BOMBAS GOULDS', motivo: 'carta poder SERMARNATH bombas' },
  { numero_oficio: 87, empresa: 'Estacionamiento español', motivo: 'Oficio PC seguimiento PC municipio ' },
  { numero_oficio: 88, empresa: 'restaurante Mama Hada ', motivo: 'Oficio PC seguimiento PC municipio ' },
  { numero_oficio: 89, empresa: "CARL´S PACHUCA ", motivo: 'Oficio PC seguimiento PC municipio ' },
  { numero_oficio: 90, empresa: 'SQG', motivo: 'Oficio PC seguimiento PC municipio MR' },
  { numero_oficio: 91, empresa: 'RV', motivo: 'Contestación STPS SEH' },
  { numero_oficio: 93, empresa: 'Puerta Niebla', motivo: 'Ingreso PC' },
  { numero_oficio: 94, empresa: 'Puerta Niebla', motivo: 'CMS ' },
  { numero_oficio: 95, empresa: 'Puerta Niebla', motivo: 'CCR' },
  { numero_oficio: 96, empresa: 'Puerta Niebla', motivo: 'Lic. func.' },
  { numero_oficio: 97, empresa: 'Oniria', motivo: 'Ingreso PC' },
  { numero_oficio: 98, empresa: 'Oniria', motivo: 'CMS ' },
  { numero_oficio: 99, empresa: 'Oniria', motivo: 'CCR' },
  { numero_oficio: 100, empresa: 'Oniria', motivo: 'Lic. func.' },
  { numero_oficio: 101, empresa: 'Reserva residencial', motivo: 'condicionantes anuales' },
  { numero_oficio: 102, empresa: 'Reserva residencial', motivo: 'termino de obra ' },
  { numero_oficio: 103, empresa: 'MAESA', motivo: 'Aclaraciones SEMARNATH' },
  { numero_oficio: 104, empresa: 'BAPEVA', motivo: 'Oficio ingreso PC Estado' },
  { numero_oficio: 105, empresa: 'BAPEVA', motivo: 'Carta poder' },
  { numero_oficio: 106, empresa: 'BAPEVA', motivo: 'Carta corresponsabilidad' },
  { numero_oficio: 107, empresa: 'DEREMATE', motivo: 'carta corresponsabilidad' },
  { numero_oficio: 108, empresa: 'DRAGON', motivo: 'factibilidad de residuos' },
  { numero_oficio: 109, empresa: 'SYCSA', motivo: 'carta poder ' },
  { numero_oficio: 110, empresa: 'BAPEVA', motivo: 'Carta compromiso OTMS estado ' },
  { numero_oficio: 111, empresa: 'BAPEVA', motivo: 'carta responsiva' },
  { numero_oficio: 112, empresa: 'RESIDENCIAL EL MARQUES', motivo: 'Factibilidad SIDPUS' },
  { numero_oficio: 113, empresa: 'RESIDENCIAL EL MARQUES', motivo: 'Factibilidad SEMARNATH' },
  { numero_oficio: 114, empresa: 'ARGENTA RESIDENCIAL', motivo: 'Carta poder' },
  { numero_oficio: 115, empresa: 'EAD', motivo: 'Oficio Pc ' },
  { numero_oficio: 116, empresa: 'EAD', motivo: 'Oficio OTMS' },
  { numero_oficio: 117, empresa: 'EAD', motivo: 'Carta corresponsabilidad' },
  { numero_oficio: 118, empresa: 'ARGENTA RESIDENCIAL', motivo: 'contestación SEMARNATH' },
  { numero_oficio: 119, empresa: 'PERDURA ', motivo: 'condicionantes anuales' },
  { numero_oficio: 120, empresa: 'CREST ', motivo: 'Condicionantes Anuales' },
  { numero_oficio: 121, empresa: 'Trituradora', motivo: 'poder' },
  { numero_oficio: 122, empresa: 'PERDURa', motivo: 'Poder' },
  { numero_oficio: 123, empresa: 'INTERCERAMIC', motivo: 'Poder' },
  { numero_oficio: 124, empresa: 'MARQUES', motivo: 'En alcance SEMARNATH' },
  { numero_oficio: 125, empresa: 'MAESA', motivo: 'Ingreso pc ' },
  { numero_oficio: 126, empresa: 'MAESA', motivo: 'Ingreso OTMS municipio' },
  { numero_oficio: 127, empresa: 'MAESA', motivo: 'carta dcorresponsabilidad ' },
  { numero_oficio: 128, empresa: 'SYCSA ', motivo: 'SYCSA condicionantes comedor' },
  { numero_oficio: 129, empresa: 'TRITURADORA ', motivo: 'SEMARNATH/DGNA/DCyE-1755/2026' },
  { numero_oficio: 130, empresa: 'TRITURADORA ', motivo: 'SEMARNATH/DGNA/DCyE-1647/2026' },
  { numero_oficio: 131, empresa: 'TRITURADORA ', motivo: 'SEMARNATH/DGNA/DCyE-1754/2026' },
  { numero_oficio: 132, empresa: 'COMEX', motivo: 'SEMARNATH reforestación' },
  { numero_oficio: 133, empresa: 'MAESA', motivo: 'Aclaración SEMARNATH' }
];

const TRAMITES_SEED = [
  { item: 1, oficio: '', accion_realizar: '', responsable: 'Biznaga', fecha_vencimiento: null, estatus: 'abierto', observaciones: '' },
  { item: 2, oficio: '', accion_realizar: '', responsable: 'Cliente', fecha_vencimiento: null, estatus: 'cerrado', observaciones: '' },
  { item: 3, oficio: '', accion_realizar: '', responsable: 'Biznaga', fecha_vencimiento: null, estatus: 'cerrado', observaciones: '' },
  { item: 4, oficio: '', accion_realizar: '', responsable: 'Cliente', fecha_vencimiento: null, estatus: 'cerrado', observaciones: '' },
  { item: 5, oficio: '', accion_realizar: '', responsable: 'Biznaga', fecha_vencimiento: null, estatus: 'cerrado', observaciones: '' },
  { item: 6, oficio: '', accion_realizar: '', responsable: 'Cliente', fecha_vencimiento: null, estatus: 'abierto', observaciones: '' },
  { item: 7, oficio: '', accion_realizar: '', responsable: 'Biznaga', fecha_vencimiento: null, estatus: 'abierto', observaciones: '' }
];

module.exports = { OFICIOS_SEED, OFICIOS_SEED_REV, TRAMITES_SEED };
